mysite/blog/urls.py
from django.urls import path

import blog.views

app_name='blog'
urlpatterns = [
    path('', blog.views.home, name="home"),
    path('blog/<int:blog_id>', blog.views.detail, name="detail"),
    path('blog/new/', blog.views.new, name="new"),
    path('blog/create/', blog.views.create, name="create"),
    path('blog/delete/<int:blog_id>', blog.views.delete, name="delete"),
    path('blog/edit/<int:blog_id>', blog.views.edit, name="edit"),
    path('blog/update/<int:blog_id>', blog.views.update, name="update"),
    path('<int:blog_id>/comment', blog.views.add_comment_to_post, name="add_comment_to_post"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name="home"),
    path('blog/<int:blog_id>', blog.views.detail, name="detail"),
    path('blog/new/', blog.views.new, name="new"),
    path('blog/create/', blog.views.create, name="create"),
    path('blog/delete/<int:blog_id>', blog.views.delete, name="delete"),
    path('blog/edit/<int:blog_id>', blog.views.edit, name="edit"),
    path('blog/update/<int:blog_id>', blog.views.update, name="update"),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=200)

    pub_date=models.DateTimeField('date published')

    body =models.TextField()

    def __str__(self):
        return self.title

    def __str__(self):
        return self.body[:100]

class Comment(models.Model):
    post=models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    author_name=models.CharField(max_length=20)
    comment_text=models.TextField()
    created_at=models.DateTimeField(default=timezone.now)

    def approve(self):
        self.save()
    
    def __str__(self):
        return self.comment_text

mysite/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('author_name', 'comment_text')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Blog
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import CommentForm

# Create your views here.

def home(request):
    blogs=Blog.objects
    return render(request, 'home.html', {'blogs':blogs})

def detail(request, blog_id):
    blog_detail=get_object_or_404(Blog, pk=blog_id)
    return render(request, 'detail.html', {'blog':blog_detail})

def new(request):
    return render(request, 'new.html')

def create(request):
    blog=Blog()
    blog.title=request.GET['title']
    blog.body=request.GET['body']

    blog.pub_date=timezone.datetime.now()
    blog.save()
    return redirect('/blog/' + str(blog.id))

def delete(request, blog_id):
    blog=Blog.objects.get(pk=blog_id)
    blog.delete()
    return redirect('home')

def edit(request, blog_id):
    blog_edit=Blog.objects.get(pk=blog_id)
    return render(request, 'edit.html', {'blog':blog_edit})

@csrf_exempt
def update(request, blog_id):
    blog=Blog.objects.get(pk=blog_id)
    blog.title=request.POST['title']
    blog.body=request.POST['body']
    blog.pub_date=timezone.datetime.now()
    blog.save()
    return redirect('home')

def add_comment_to_post(request, blog_id):
    blog=get_object_or_404(Blog, pk=blog_id)
    if request.method =="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=blog
            comment.save()
            return redirect('blog:detail', blog_id)
    else:
        form=CommentForm()
    return render(request, 'add_comment_to_post.html', {'form':form})

mysite/blog/templates/add_comment_to_post.html
{% block content %}
<h1> New Comment</h1>
<form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Send</button>
</form>
{% endblock %}

mysite/blog/templates/detail.html
<h1> detail 페이지 </h1>

<div class="container">
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.pub_date}}</p>
    <p>{{blog.body}}</p>
    <a calss="btn btn-default" href="{% url 'blog:add_comment_to_post' blog.id %}">댓글달기</a>
    <a calss="btn btn-default" href="{% url 'blog:home' %}">돌아가기</a>

    <hr>
    {% for comment in blog.comments.all %}
    <div class="comment">
        <div class="date">{{comment.created_at}}</div>
        <strong>{{comment.author_name}}</strong>
        <p>{{comment.comment_text}}</p>
    </div>
    {%empty%}
        <p>No comments here yet :( </p>
    {% endfor %}
</div>

mysite/blog/templates/edit.html
<div class="container">
    <form action="{% url 'blog:update' blog.id %}" method="POST">
        {% csrf_token %}
        <h4>제목 : </h4>
        <input type="text" name="title"  value="{{blog.title}}">
        <br>
        <br>
        <h4>본문 : </h4>
        <textarea cols=40 rows=10 name="body">{{blog.body}}</textarea>
        <br>
        <br>
        <input class="btn btn-dark" type="submit" value="제출하기">
    </form>
</div>

mysite/blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">LIKELION</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button type="button" class="btn btn-warning">Post</button>
          </form>
        </div>
      </nav>


<h1>MY HOMEPAGE❤</h1>

{% for blog in blogs.all %}
    <div class="container">
        <h1>{{ blog.title }}</h1>
        <p>{{ blog.pub_date}}</p>
        <p>{{blog.summary}}<a href="{% url 'blog:detail' blog.id %}">...more</a></p>
        <p><a href="{% url 'blog:delete' blog.id %}" style='text-decoration: none;'>삭제</a></p>
        <p><a href="{% url 'blog:edit' blog.id %}">수정</a></p>
    </div>
{% endfor %}

<div class="navbar">
    <a class ="nav-item nav-link" href="{% url 'blog:home' %}">Home</spa></a>
    <a class ="nav-item nav-link" href="{% url 'blog:new' %}">글쓰기</a>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

mysite/blog/templates/new.html
<div class="container">
    <form action="{% url 'create' %}">
        <h4>제목 : </h4>
        <input type="text" name="title">
        <br>
        <br>
        <h4>본문 : </h4>
        <textarea cols=40 rows=10 name="body" ></textarea>
        <br>
        <br>
        <input class="btn btn-dark" type="submit" value="제출하기">
    </form>
</div>